from datetime import datetime
from pathlib import Path
import base64

from playwright.sync_api import sync_playwright

# Change this to any site that loads reliably for your demo
URL = "https://playwright.dev/docs/intro"  # stable demo target

OUTDIR = Path("runs") / ("edge_demo_" + datetime.now().strftime("%Y%m%d_%H%M%S"))
OUTDIR.mkdir(parents=True, exist_ok=True)

def img_to_data_uri(png_path: Path) -> str:
    data = png_path.read_bytes()
    b64 = base64.b64encode(data).decode("utf-8")
    return f"data:image/png;base64,{b64}"

with sync_playwright() as p:
    # Option A: Launch installed Microsoft Edge via channel
    browser = p.chromium.launch(channel="msedge", headless=False)  # uses Edge [2](https://github.com/microsoft/playwright-python/issues/1227)
    page = browser.new_page()

    # Collect basic info
    started = datetime.now().isoformat(timespec="seconds")
    page.goto(URL, wait_until="domcontentloaded", timeout=60000)
    page.wait_for_timeout(1500)
    title = page.title()

    # Screenshot evidence
    shot_path = OUTDIR / "page.png"
    page.screenshot(path=str(shot_path), full_page=True)

    browser.close()

# Build a simple HTML report
report_path = OUTDIR / "report.html"
img_uri = img_to_data_uri(shot_path)

html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>UI Evidence Report (Edge)</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; }}
    .meta {{ background:#f5f5f5; padding:12px; border-radius:8px; }}
    img {{ max-width: 100%; border: 1px solid #ddd; border-radius: 8px; }}
    code {{ background:#eee; padding:2px 6px; border-radius:4px; }}
  </style>
</head>
<body>
  <h1>UI Evidence Report (Microsoft Edge)</h1>
  <div class="meta">
    <p><b>Run time:</b> {started}</p>
    <p><b>URL:</b> <a href="{URL}">{URL}</a></p>
    <p><b>Page title:</b> {title}</p>
    <p><b>Evidence:</b> Full-page screenshot captured from Edge.</p>
  </div>
  <h2>Screenshot Evidence</h2>
  <img src="{img_uri}" alt="UI Screenshot Evidence"/>
  <p style="margin-top:16px;color:#666;">Generated by Playwright + Python using installed Microsoft Edge.</p>
</body>
</html>
"""

report_path.write_text(html, encoding="utf-8")
print(f"✅ Report generated: {report_path}")
print(f"✅ Screenshot saved: {shot_path}")